steps:
  # Build the container image and push it with Kaniko
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
    - --cache=true
    - --cache-ttl=6h
    - --destination=us-central1-docker.pkg.dev/eighth-vehicle-375706/kaniko-demo/executor:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY